### ISSUE TITLE
Bug, Socket keeps returning 400

### ISSUE THREAD

**Issue by PatrykDubinski** [notum-cz/strapi-plugin-record-locking#4]
In dev environment the plugin works well but on production env socket keeps retrying connection and it returns 400 with message "Unknown session ID"

![Zrzut ekranu 2022-06-13 o 11 25 09](https://user-images.githubusercontent.com/71813865/173323024-bfea02a4-22f0-4419-88d2-7655fc3ef1ec.png)

**Comment by Fikoun** [comment]
> socket keeps retrying connection and it returns 400 with message "Unknown session ID"

Couldn't replicate your bug, can you try reinstaling with the new versions and specify difference in your configurations (dev/prod).

**Comment by medina-demirova** [comment]
We have the same issue on production and master, and this happens when we have 2 pod replicas in Kubernetes.

**Comment by omikulcik** [comment]
Hi @medina-demirova, we will soon publish a new version of this plugin so hopefully by updating dependencies etc. your problem may be fixed.

**Comment by omikulcik** [comment]
@medina-demirova We have just published a new version. Can you please try if it solves your problem?

**Comment by Krofer** [comment]
I have the same error :) I happens because we have 3 pod replicas in Kubernetes and plugin send a couple of request POST /socket.io/?EIO=4&transport=polling&t=OlsQIMD and GET

Because we have 3 pods all of request sent to another pods each time and we lost consistency

I guess the good way to fix it - move save session id to redis for example

**Comment by Krofer** [comment]
Hi! I fixed this problem it PR - https://github.com/notum-cz/strapi-plugin-record-locking/pull/55

Check and ask questions, please :)

**Comment by Shaderpixel** [comment]
Hi @Krofer  thanks for this plugin, we are now using v1.3.8 with Strapi v4.9 and still seeing this issue. Some went through fine but others starts erroring: see screenshots. Let me know what other information that I can provide.

<img width="1054" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/12938414/96355c86-54be-43bd-81de-90e49deeb21c">

<img width="1362" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/12938414/cc8cc033-a099-4df6-a0b8-7021e4506870">

<img width="1092" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/12938414/44152ecd-8876-4123-a3fd-a3efd0995412">

**Comment by omikulcik** [comment]
Hey @Shaderpixel, do you also use Kubernetes or is this another case please?

**Comment by disfear-eng** [comment]
Hi, we are using v1.3.15 and plugin settings not working.
This has been fixed in v2, would it be possible to fix it in v1.x?

[EntityLock/index.tsx#L65(v1.3.15)](https://github.com/notum-cz/strapi-plugin-record-locking/blob/v1.3.15/admin/src/components/EntityLock/index.js#L65)

[EntityLock/index.tsx#L52(v2.0.0)](https://github.com/notum-cz/strapi-plugin-record-locking/blob/v2.0.0/admin/src/components/EntityLock/index.tsx#L52)
